wrf_variables:
  BT
  CFtotal
  CFlow
  DZ700-850
  GPZ500
  GPZ700 
  GPZ850 
  Helicity 
  LCL 
  PLI
  PW
  Rain
  RH500
  RH700
  RH2 
  RH850 
  RH800 
  SHOW 
  SLP 
  Td500 
  Td2
  T2 
  T750 
  T500 
  T850 
  TT 
  W500 